name: macOS

on: [push]

jobs:
  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Setup
        run: sh -c "`curl -fsSL https://raw.githubusercontent.com/hir0o/dotfiles/feature/add-test/install.bash`"
